export const RMQ_SERVICE = 'RMQ_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const ORGANIZATION_SERVICE = 'ORGANIZATION_SERVICE';
export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE';
export const MEDIA_SERVICE = 'MEDIA_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const ORDERS_SERVICE = 'ORDERS_SERVICE';

// Events
export const ORGANIZATION_EVENTS_CLIENT = 'ORGANIZATION_EVENTS_CLIENT';
export const NOTIFICATIONS_EVENTS_CLIENT = 'NOTIFICATIONS_EVENTS_CLIENT';
export const PAYMENTS_EVENTS_CLIENT = 'PAYMENTS_EVENTS_CLIENT';
export const STRIPE_CLIENT = 'STRIPE_CLIENT';
